language: php
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- '7.4'
- 'nightly'
jobs:
  allow_failures:
    - php: 'nightly'
before_script:
- composer require --dev phpunit/phpunit $PHPUNIT_VERSION
- composer require --dev phpunit/php-code-coverage
- phpenv config-rm xdebug.ini
script:
- ./vendor/bin/phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
- cd ..
- mkdir packages
- zip -r packages/tpl_trta.zip tpl_trta/src -x \*.git\*
- git clone -b 1.0.0 https://github.com/Gileba/plg_system_templatecompanion.git plg_system_templatecompanion
- cd plg_system_templatecompanion/src; zip -r ../../packages/plg_system_templatecompanion.zip * -x \*.git\* *.gitignore*; cd ../../
- cp tpl_trta/pkg_trta.xml pkg_trta.xml
- zip pkg_trta packages/tpl_trta.zip packages/plg_system_templatecompanion.zip pkg_trta.xml
deploy:
  provider: releases
  edge: true
  file:
  - packages/tpl_trta.zip
  - pkg_trta.zip
  on:
    tags: true
  token: $GITHUB_TOKEN
after_deploy: curl -T tpl_trta/tpl_trta.xml -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
